### PR TITLE
Providing static website demo of every pull request, updated in place on each new commit

### PR DESCRIPTION
**Pull request by giorgiosironi**
1. Go to `All checks have passed`
2. Click on `Show all checks`
3. Click the `Details` link of `continuous-integration/jenkins/pr-demo`
4. Enjoy the demo with shareable URL to send to product

### CODE REVIEW

**Comment by elife-alfred-user** [comment]
I'm elife-alfred-user and I want to post a comment here (manually through the Github UI).

**Comment by elife-alfred-user** [comment]
You can see this pattern-library version at https://s3.amazonaws.com/ci-pattern-library/738/index.html

**Comment by giorgiosironi** [comment]
First thought: store state on the filesystem as we do for events. Won't work very well as libraries are build on slave nodes rather than on the master.

**Comment by giorgiosironi** [comment]
Looking for an existing comment with a similar text is slower (one more API call) but reliable, it is not flexible enough to be reused for other actions but a good-enough solution for this case.

**Comment by thewilkybarkid** [comment]
Could we do what we had with Platform.sh, so it's a separate build? There wouldn't be that problem then.

Think it would be useful to separate code checks and tests in the same way.

**Comment by giorgiosironi** [comment]
We can have a separate and parameterized build triggered with the commit sha from here once the tests pass (or even before); but there is a dependency as the output used to populate the bucket is the current content of `pattern-library--ci` so we would have to do the same Salt highstate twice. Would also still be 1 comment for every commit, which is not what we want.

Unless we want to trigger it manually, but it's annoying to click around for every update to the code that needs to be published.

**Comment by thewilkybarkid** [comment]
I mean the link to the deploy is the build's 'Details' link, rather than a comment.

**Comment by giorgiosironi** [comment]
We have some code around to notify arbitrary Git commit statuses, will check if it works in this case.

**Comment by giorgiosironi** [comment]
Ok, provided in the `Static website` link.

**Pull request merged**
