### PR TITLE
Remove teaser's span

### PR DESCRIPTION
**Pull request by viktoria-mahmud**
Change HTML on one line to trim the spaces in the content

### CODE REVIEW

**Review by Cosmin-Daniel — APPROVED** [review]

**Review by discodavey — APPROVED** [review]
Looks good to me. Any comments @nlisgo?

**Comment by nlisgo** [comment]
@discodavey is there any part of this that you want to draw my attention to for comment?

**Comment by discodavey** [comment]
> @discodavey is there any part of this that you want to draw my attention to for comment?

Nothing really. Just a quick scan to be honest

**Review by discodavey — APPROVED** [review]

**Review by nlisgo — APPROVED** [review]
:rocket:

**Pull request merged**
