### PR TITLE
Fix Highlights on Safari

### PR DESCRIPTION
**Pull request by Cosmin-Daniel**

### CODE REVIEW

**Review by viktoria-mahmud — APPROVED** [review]
I can't check it on Safari but it still looks fine on other browsers

**Comment by chris-huggins** [comment]
Thanks @Cosmin-Daniel. It appears to have been solved, but there's something pushing down the title of the third link and I can't tell why, or if it's related. It does appear in other browsers though, so I assume not related to the bug? But seems to be a result of this PR.

image

**Comment by Cosmin-Daniel** [comment]
> Thanks @Cosmin-Daniel. It appears to have been solved, but there's something pushing down the title of the third link and I can't tell why, or if it's related. It does appear in other browsers though, so I assume not related to the bug? But seems to be a result of this PR.
> 
> image

@chris-huggins you are right, the content wasn't well aligned. I've fixed that. Could you please check it again?

**Review by chris-huggins — APPROVED** [review]

**Comment by chris-huggins** [comment]
Thanks @Cosmin-Daniel Looks good to me too.

**Comment by discodavey** [comment]
Looking in pattern library in Organisms the full highlights (three items) and also two items are doing weird things as well.
Screenshot 2023-01-18 at 11 13 00
Screenshot 2023-01-18 at 11 16 23

**Review by discodavey — COMMENTED** [review]
All looks ok with me

**Pull request merged**
