### PR TITLE
Extract authors and institutions into separate template

### PR DESCRIPTION
**Pull request by nlisgo**

### CODE REVIEW

**Comment by nlisgo** [comment]
Here is a demo instance of journal with this work incorporated: https://pr-1609--journal.elifesciences.org

**Review by discodavey — CHANGES_REQUESTED** [review]
Looks good but needs some styling in the authors molecule for padding between authors and institutes.

**Comment by nlisgo** [comment]
> Looks good but needs some styling in the authors molecule for padding between authors and institutes.

@discodavey I think the padding is only present on the content header redesign and this PR is intended to maintain the same presentation as is currently implemented on the live site.

**Review by discodavey — APPROVED** [review]
All looks good from testing

**Pull request merged**
