### PR TITLE
Allow for export to npm

### PR DESCRIPTION
**Pull request by nlisgo**

### CODE REVIEW

**Comment by nlisgo** [comment]
@NuclearRedeye could you publish these changes to npm. Have bumped the version to `0.0.2`. I still can't login to npm. :(

**Comment by NuclearRedeye** [comment]
@nlisgo Done, once this is merged can you please raise a new issue so that we can update this package to get the CI to publish to npm automatically.

**Comment by nlisgo** [comment]
> @nlisgo Done, once this is merged can you please raise a new issue so that we can update this package to get the CI to publish to npm automatically.

I still can't manually publish the npm package, the credentials you sent aren't working for me. Are you able to do that but it would be good to sort that out too. There should be more than just yourself that can publish to npm manually.

I will create the followup ticket now to handle the automation of this process.

**Comment by nlisgo** [comment]
@NuclearRedeye here is the followup ticket: https://github.com/elifesciences/issues/issues/5702

**Comment by nlisgo** [comment]
@NuclearRedeye have you been able to publish the npm package again?

**Comment by NuclearRedeye** [comment]
@nlisgo I published v0.0.2 when you previously asked, is that OK? And yes need to figure out why you couldn't publish, suspect that you npm version might be old?

**Pull request merged**
