### PR TITLE
Remove span for content headers

### PR DESCRIPTION
**Pull request by viktoria-mahmud**

### CODE REVIEW

**Comment by discodavey** [comment]
Looks ok from what I can see. This needs to be done on teasers as well. Will get a ticket created for that as well.

**Comment by nlisgo** [comment]
@discodavey have you completed review on this?

**Comment by discodavey** [comment]
Not looked at this in local but was there any styles in the class 'content-header__subject' and if so where have they been put as there are no changes to the css?

**Comment by viktoria-mahmud** [comment]
> Not looked at this in local but was there any styles in the class 'content-header__subject' and if so where have they been put as there are no changes to the css?

The class "content-header__subject" was added on the span element and it is removed from the project now, most of the style is moved to the parent element "content-header__subject_link".

**Review by discodavey — APPROVED** [review]

**Review by nlisgo — APPROVED** [review]

**Comment by nlisgo** [comment]
:ship:

**Pull request merged**
