### PR TITLE
Removing as causing weird issues with links

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
I am pushing this through to see what it looks like on a journal temp PR as I think this may cause other issues. This looks ok in Pattern Library at the moment but if there are issues then we will need to add them to Pattern Library for future reference.

**Comment by nlisgo** [comment]
I'm going to deploy this through to a demo instance of journal.

**Comment by discodavey** [comment]
@scottaubrey or @nlisgo Can you please review this code please as I need to get this live this morning.

**Comment by discodavey** [comment]
Going to merge this into master.

**Pull request merged**
