### PR TITLE
Accessibility changes phase2

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
@nlisgo Can you just approve as waiting for Chris H to look at the pattern.

**Comment by nlisgo** [comment]
There's a lot to review here. Maybe jump on a call and talk me through it?

**Comment by discodavey** [comment]
Can do.. Chris and I was doing a lot of changes this morning

**Review by nlisgo — APPROVED** [review]

**Comment by discodavey** [comment]
@nlisgo Do you need to do anything or can I just merge as normal?

**Pull request merged**
