### PR TITLE
Remove carousel item pattern and move examples to carousel

### PR DESCRIPTION
**Pull request by nlisgo**
As carousel item is not currently work or any of it's variants, I have moved all of the variants into carousel in the `organisms` section and have moved the `scss` and template and schema to the `carousel` template.

### CODE REVIEW

**Review by discodavey — APPROVED** [review]
Just tested this and all looks ok. Did you just copy and paste the CSS over from the old files? If so then good to go.

**Comment by nlisgo** [comment]
> Just tested this and all looks ok. Did you just copy and paste the CSS over from the old files? If so then good to go.

Yes, I have copied the css from `assets/sass/patterns/molecules/carousel-item.scss` to `assets/sass/patterns/organisms/carousel.scss `: https://github.com/elifesciences/pattern-library/pull/1050/files#diff-3eeb7f47b47117e62a9a9fd84011a8bacc09e3efbdbba5ce3a76841b4410a385

**Comment by nlisgo** [comment]
Before merging this in, I will prepare the `patterns-php` and maybe even the `journal` changes. Knowing what the challenges may be there may determine a different approach here.

**Comment by nlisgo** [comment]
Closing, in favour of https://github.com/elifesciences/pattern-library/pull/1051

**Pull request closed without merging**
